### ISSUE TITLE
Template does not allow multiple mentions of the same interface (e.g. for adding additional addresses)

### ISSUE THREAD

**Issue by felixb** [Oefenweb/ansible-network-interfaces#14]
I configured the role like this based on hints from https://wiki.debian.org/NetworkConfiguration#Network_Interface_Names:
```
    network_interfaces_interfaces:
      - device: "{{ ansible_interfaces | select('match', '^en') | list | first }}"
        auto: true
        family: inet
        method: dhcp
      - device: "{{ ansible_interfaces | select('match', '^en') | list | first }}"
        auto: true
        family: inet
        method: static
        address: '192.168.178.4'
```

I'd expect an output like this:
```
# Ansible managed

auto enx001e06360900
iface enx001e06360900 inet dhcp

iface enx001e06360900 inet static
  address 192.168.178.4
```

Instead I got this (which destroys connectivity):

```
# Ansible managed

auto enx001e06360900
iface enx001e06360900 inet static
  address 192.168.178.4
```
