### ISSUE TITLE
Add interface vlan

### ISSUE THREAD

**Issue by Cormoran96** [Oefenweb/ansible-network-interfaces#17]
It would be nice to be able to add vlan interfaces

**Comment by FrankGiesecke** [comment]
VLAN interfaces can be managed by using the vlan annotation as device name:
```yaml
network_interfaces_interfaces:
  - device: eth0.1
    ...
```

But to do this, https://github.com/Oefenweb/ansible-network-interfaces/pull/11 have to be merged. Otherwise ansible will run into an error because the interface isn't present before it was created.
